### ISSUE TITLE
help！！！

### ISSUE THREAD

**Issue by yyues** [antd-templater/library-3.x#4]
有一些问题，作者看到可以回答一下，非常感谢！！！！
1、export 导出的字段在vscode里 没有相应的类型提示，这个是需要配置tsConfigs吗？ /resolve,可以正常使用，但没有类型提示
2、通过 package-name/dist/S-Ellipsis 这样直接访问报错了，

感谢up！！！

**Comment by yyues** [comment]
第二点有解决方法了

**Comment by linpengteng** [comment]
<img width="1901" alt="image" src="https://github.com/user-attachments/assets/c17c1b52-799d-470c-ab1b-b3a17d8cd413">

具体可以参考： https://antd-templater.github.io/docs/vue3.x/library/quick.html

**Comment by linpengteng** [comment]
1。 那我理解错了，"@antd-templater/library-3.x/globals" 并没有提供像 isArray API typescript，有关 globals.d.ts 内容，你可以看 src/typing/globals.d.ts

2. 由于tsconfig.ts 配置的缘故，无法使用 `import { isArray } from '@antd-templater/library-3.x/helper'`
```typescript
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "Bundler",
  }
}
```

除非在 package.json 里配置，像下面这样

```json
{
  "name": "@antd-templater/library-3.x",
  "main": "./dist/index.cjs",
  "types": "./dist/index.d.ts",
  "module": "./dist/index.mjs",
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "import": "./dist/index.mjs",
      "require": "./dist/index.cjs"
    },
    "./helper": {
      "types": "./dist/helper.d.ts",
      "import": "./dist/helper.mjs",
      "require": "./dist/helper.cjs"
    },
  },
}
```

3. 但是我更推荐使用 `js-simpler`, 本身 `@antd-templater/library-3.x` 的 helper 大部分API，也是从 `js-simpler` import 导入。
 
 `js-simpler`： https://github.com/linpengteng/js-simpler

**Comment by linpengteng** [comment]
如果解决了你的问题，到时候关闭下这个 issues～

**Comment by yyues** [comment]
好滴，感谢

**Comment by yyues** [comment]
thank you
